# -*- coding: utf-8 -*-
"""leitura_de arquivo_excel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feLd3RY4fqoeyRTk-1h64ico5HZIlK_T
"""

## Vamos importar as bibliotecas para podemos usar o Pandas e o driver do Google Driver
import pandas as pd
from google.colab import drive

# Montar o Google Drive
drive.mount('/content/drive')

# Temos duas situaçao, podemos ditar o diretorio ou fixar o mesmo

##file_path = input("Enter the file path of the Excel file: ")
file_path = '/content/drive/MyDrive/notebooks_unialfa/excel/exemplo.xlsx'

# Aqui vai realizar a leituro do arquivo excel
df = pd.read_excel(file_path)

# Vamos realizar o print dos dados
print(df)

# Temos duas situaçao, podemos ditar o diretorio ou fixar o mesmo

##file_path = input("Enter the file path of the Excel file: ")
file_path = '/content/drive/MyDrive/notebooks_unialfa/excel/exemplo.xlsx'

# Aqui vai realizar a leituro do arquivo excel
df = pd.read_excel(file_path)

# Vamos realizar o print dos dados de forma tabulas
print(df.head())  # Isso imprimirá as primeiras 5 linhas por padrão

# Defina o caminho do arquivo Excel
# file_path = input("Enter the file path of the Excel file: ")
file_path = '/content/drive/MyDrive/notebooks_unialfa/excel/exemplo.xlsx'

# Carregue o arquivo Excel
xls = pd.ExcelFile(file_path)

# Obtenha uma lista de nomes de planilhas no arquivo Excel
sheet_names = xls.sheet_names

# Imprima os nomes das planilhas
for sheet_name in sheet_names:
    print(sheet_name)

# Defina o caminho do arquivo Excel
# file_path = input("Enter the file path of the Excel file: ")
file_path = '/content/drive/MyDrive/notebooks_unialfa/excel/exemplo.xlsx'

# Especifique o nome da planilha que você deseja ler
sheet_name = 'dim_cliente'  # Substitua 'Nome_da_sua_planilha' pelo nome real da planilha

# Realize a leitura da planilha especificada
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Defina o número máximo de linhas a serem exibidas
max_rows_to_display = 100  # Defina o número de linhas que deseja exibir

# Imprimir as primeiras max_rows_to_display linhas
print(df.head(max_rows_to_display).to_string(index=False))

# Defina o caminho do arquivo Excel
# file_path = input("Enter the file path of the Excel file: ")
file_path = '/content/drive/MyDrive/notebooks_unialfa/excel/exemplo.xlsx'

# Especifique o nome da planilha que você deseja ler
sheet_name = 'dim_cliente'  # Substitua 'Nome_da_sua_planilha' pelo nome real da planilha

# Realize a leitura da planilha especificada
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Defina o número máximo de linhas a serem exibidas
max_rows_to_display = 100  # Defina o número de linhas que deseja exibir

# Imprimir as primeiras max_rows_to_display linhas
# print(df.head(max_rows_to_display).to_string(index=False))

# Se você souber a linha e a coluna onde o valor específico está localizado, pode usar iloc para acessá-lo.
valor = df.iloc[4, 1]  # Linha 5 (o índice é baseado em zero), coluna 2
print("Valor selecionado pelo indice:", valor)

## Se você souber o rótulo das linhas e das colunas, pode usar loc. Por exemplo, se a primeira coluna do DataFrame for uma coluna de rótulos (por exemplo, IDs de cliente)
## e você quiser selecionar o valor correspondente ao cliente com ID 123:
valor = df.loc[df['CODIGO_CLIENTE'] == 34941, 'RAZAOSOCIAL']  # Substitua 'ID_cliente' pelo nome real da coluna de ID do cliente
print("Valor selecionado pelo codigo do cliente:", valor.values[0])  # Use .values[0] para obter o valor como um escalar

